# Generated by Django 5.2.4 on 2025-07-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0002_swaggerproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwaggerEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('url_complete', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scraping_data.swaggerproject')),
            ],
        ),
    ]
