# Generated by Django 5.2.4 on 2025-07-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0003_swaggerendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('url_complete', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('cleaned_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('path_variables', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scraping_data.swaggerproject')),
            ],
        ),
        migrations.DeleteModel(
            name='SwaggerEndpoint',
        ),
    ]
